In [6]:
import os
import h5py
import pandas as pd
import numpy as np

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

path = './kastner_generation_05_01_2024.hdf5'

f = h5py.File(path, 'r')
f2 = h5py.File('./gillanData.h5', 'r')

In [41]:
arr = f['episode_data'][:]
arr.shape


rews = arr[:, :, 3]
arr2 = arr[:, :, 0:2].reshape(arr.shape[0], -1)
arr2.shape
arr2[:, 1::2] = arr2[:, 1::2] + 2  # 0/1 stage 2 -> 2/3
rews.shape

rews2 = np.zeros(arr2.shape)
rews2[:, 1::2] = rews
rews2.shape

arr3 = np.stack((arr2, rews2), axis=-1)
arr3.shape

(26101, 200, 4)

(26101, 400)

(26101, 200)

(26101, 400)

(26101, 400, 2)

In [46]:
arr3.shape
arr3.transpose(1, 2, 0).shape

(26101, 400, 2)

(400, 2, 26101)

In [7]:
print(list(f.keys()))
print(list(f2.keys()))

['episode_data', 'model_params']
['allData']


In [10]:
f2['allData']

<HDF5 dataset "allData": shape (400, 2, 1413), type "|u1">

In [14]:
f2['allData'][:].shape

f2['allData'][:]

(400, 2, 1413)

array([[[0, 0, 1, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[2, 2, 3, ..., 3, 3, 2],
        [1, 1, 0, ..., 1, 0, 1]],

       [[1, 0, 1, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[3, 5, 3, ..., 3, 2, 3],
        [0, 0, 0, ..., 0, 0, 1]],

       [[1, 4, 1, ..., 1, 0, 1],
        [0, 0, 0, ..., 0, 0, 0]],

       [[3, 5, 3, ..., 3, 2, 3],
        [1, 0, 0, ..., 1, 0, 1]]], dtype=uint8)

In [18]:
from collections import Counter
c = Counter(f2['allData'][:][:, 0, :].flatten())
c

Counter({0: 154389, 1: 126259, 4: 1952, 2: 107745, 3: 171923, 5: 2932})

In [19]:
c2 = Counter(f2['allData'][:][:, 1, :].flatten())
c2

Counter({0: 413802, 1: 151398})

In [22]:
arr = f2['allData'][:]
arr = arr.transpose(2, 0, 1)
arr.shape

(1413, 400, 2)

In [31]:
arr[0, 0::2, 0]  # first stage
arr[0, 1::2, 0]  # second stage
arr[0, 0::2, 1]  # first stage reward is always 0
arr[0, 1::2, 1]  # second stage reward is either 0 or 1

array([0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 4, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1], dtype=uint8)

array([2, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 3, 3, 2, 3, 3, 2, 2, 3, 2, 3,
       3, 2, 2, 2, 2, 3, 3, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3,
       2, 2, 2, 2, 3, 2, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 2, 2, 2, 2, 3,
       3, 3, 3, 2, 3, 3, 3, 2, 3, 2, 2, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 2,
       3, 3, 3, 2, 3, 3, 3, 2, 2, 2, 3, 5, 3, 3, 2, 2, 3, 3, 3, 2, 3, 2,
       3, 2, 3, 2, 3, 3, 3, 3, 2, 3, 2, 3, 2, 3, 3, 3, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 2, 2, 3, 2, 3, 3, 2, 2, 3, 3, 3, 2, 3, 3, 2, 3, 3,
       3, 3, 2, 3, 3, 2, 3, 3, 3, 3, 2, 2, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3,
       2, 2, 3, 2, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3], dtype=uint8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0], dtype=uint8)

array([1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1], dtype=uint8)

In [35]:
subj = arr[0]  # I transposed 400 x 2 x N -> N x 400 x 2
subj[0::2, 0]  # first stage
subj[1::2, 0]  # second stage
subj[0::2, 1]  # first stage reward is always 0
subj[1::2, 1]  # second stage reward is either 0 or 1

array([0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 4, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1], dtype=uint8)

array([2, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 3, 3, 2, 3, 3, 2, 2, 3, 2, 3,
       3, 2, 2, 2, 2, 3, 3, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3,
       2, 2, 2, 2, 3, 2, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 2, 2, 2, 2, 3,
       3, 3, 3, 2, 3, 3, 3, 2, 3, 2, 2, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 2,
       3, 3, 3, 2, 3, 3, 3, 2, 2, 2, 3, 5, 3, 3, 2, 2, 3, 3, 3, 2, 3, 2,
       3, 2, 3, 2, 3, 3, 3, 3, 2, 3, 2, 3, 2, 3, 3, 3, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 2, 2, 3, 2, 3, 3, 2, 2, 3, 3, 3, 2, 3, 3, 2, 3, 3,
       3, 3, 2, 3, 3, 2, 3, 3, 3, 3, 2, 2, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3,
       2, 2, 3, 2, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3], dtype=uint8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0], dtype=uint8)

array([1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1], dtype=uint8)

In [33]:
arr_b = f['episode_data'][:]
arr_b

array([[[0, 0, 0, 1],
        [0, 0, 1, 0],
        [1, 1, 0, 0],
        ...,
        [1, 1, 0, 0],
        [0, 0, 1, 1],
        [1, 0, 1, 0]],

       [[0, 0, 0, 1],
        [0, 0, 0, 1],
        [1, 1, 0, 1],
        ...,
        [1, 1, 1, 0],
        [0, 0, 0, 1],
        [0, 0, 0, 0]],

       [[0, 0, 0, 1],
        [1, 1, 0, 0],
        [1, 1, 1, 1],
        ...,
        [0, 0, 1, 1],
        [0, 0, 1, 1],
        [1, 0, 1, 0]],

       ...,

       [[0, 0, 0, 1],
        [0, 1, 1, 0],
        [0, 0, 0, 1],
        ...,
        [1, 1, 0, 0],
        [0, 0, 1, 1],
        [0, 1, 1, 0]],

       [[0, 0, 0, 0],
        [1, 1, 1, 0],
        [0, 0, 0, 1],
        ...,
        [1, 1, 0, 1],
        [1, 0, 0, 0],
        [1, 1, 0, 1]],

       [[0, 0, 1, 0],
        [1, 1, 0, 1],
        [1, 1, 0, 1],
        ...,
        [1, 1, 0, 1],
        [0, 1, 0, 1],
        [1, 0, 0, 1]]], dtype=uint8)

In [34]:
arr_b.shape

(26101, 200, 4)